language: python

sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
      - expect-dev
      - python-lxml
      - python-simplejson
      - python-yaml
      - swig  # Required for m2crypto
      - python-m2crypto
      - xmlstarlet
      - xsltproc
      - xmlstarlet
      - openssl
      - poppler-utils
      - antiword

python:
  - "3.5"
env:
  global:
  - LINT_CHECK="0" TESTS="0"
  - VERSION="11.0" ODOO_REPO="vauxoo/odoo"
  - INCLUDE="asdcust"
  matrix:
  - LINT_CHECK="1"
  - TESTS="1"

install:
  - git clone --single-branch --depth=1 https://github.com/vauxoo-dev/maintainer-quality-tools.git -b master-enable-unnecessary-utf8-coding-comment-jesuszapata ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - if [[ "${ENTERPRISE}" == "1" ]]; then git clone git@github.com:Vauxoo/enterprise.git -b $VERSION ${HOME}/enterprise; fi
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
